[package]
name = "keypsake"
version = "0.1.0"
edition = "2021"
author = "Christian Christovich"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
